baseurl: /
title: A Claquete
languageCode: pt-br
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author:
  avatar: img/avatar.png
  bio: Graduado em Cinema com especialização em Roteiro e crítico de Cinema.
  name: Guilherme Cândido
Params:
  authorbox: yes
  description: John Doe's Personal blog about everything
  logo:
    subtitle: A FINA FLOR DO CINEMA
  mainSections:
    - post
    - docs
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
